import userImg from "../assets/image/svg/user-img.svg";
import dots from "../assets/image/svg/dots.svg";

export const userData = [
  {
    img: userImg,
    dotImg: dots,
    name: "John deo",
    email: "john.deo@gmail.com",
    ragistrationDate: "01-01-2023",
    city: "Hisar",
    state: " Haryana",
    stuts: "Active",
    investments: "₹ 32,460.00",
  },
  {
    img: userImg,
    dotImg: dots,
    name: "John deo",
    email: "john.deo@gmail.com",
    ragistrationDate: "01-01-2023",
    city: "Hisar",
    state: " Haryana",
    stuts: "Active",
    investments: "₹ 32,460.00",
  },
  {
    img: userImg,
    dotImg: dots,
    name: "John deo",
    email: "john.deo@gmail.com",
    ragistrationDate: "01-01-2023",
    city: "Hisar",
    state: " Haryana",
    stuts: "Active",
    investments: "₹ 32,460.00",
  },
  {
    img: userImg,
    dotImg: dots,
    name: "John deo",
    email: "john.deo@gmail.com",
    ragistrationDate: "01-01-2023",
    city: "Hisar",
    state: " Haryana",
    stuts: "Active",
    investments: "₹ 32,460.00",
  },
  {
    img: userImg,
    dotImg: dots,
    name: "John deo",
    email: "john.deo@gmail.com",
    ragistrationDate: "01-01-2023",
    city: "Hisar",
    state: " Haryana",
    stuts: "Active",
    investments: "₹ 32,460.00",
  },
];
